### ISSUE TITLE
No .bin after install command

### ISSUE THREAD

**Issue by fhjer** [meff34/docsify-to-pdf-converter#5]
I have some issues to ask about install the js.
Firstly, I didn't find the  folder **.bin** under `../node_modules/docsify-pdf-converter` after installing the js successfully. Why? 
Secondly, I download it from this site, is it right? Howerver, it throws the error: `Error: Cannot find module 'rcfile'`，how to solve it?

**Comment by meff34** [comment]
Hello, @fhjer.

I'm sorry for the long answer, it caused by my work on other projects.
If your problem is actual and for the history: you must install this package through a package manager like this:
```
npm install --save-dev docsify-pdf-converter
```
or
```
yarn add docsify-pdf-converter --dev
```
if you using `yarn`.

The package manager will create folder `.bin` just inside your `node_modules`.

Feel free to reopen this issue, if you have some troubles!
